# Generated by Django 4.1 on 2023-03-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_blog_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='favourites',
        ),
    ]
